# Generated by Django 6.0.3 on 2026-05-15 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_customer_email_order_customer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('images_purged_at', models.DateTimeField(blank=True, null=True)),
                ('purge_task_id', models.CharField(blank=True, max_length=120)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='orders.order')),
            ],
            options={
                'db_table': 'order_chats',
            },
        ),
        migrations.CreateModel(
            name='OrderChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_kind', models.CharField(choices=[('customer', 'Customer'), ('restaurant', 'Restaurant'), ('guest', 'Guest')], max_length=20)),
                ('sender_label', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='order-chat/%Y/%m/')),
                ('image_purged', models.BooleanField(default=False)),
                ('read_by_customer_at', models.DateTimeField(blank=True, null=True)),
                ('read_by_restaurant_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='order_chat.orderchat')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_chat_messages',
                'indexes': [models.Index(fields=['chat', 'created_at'], name='order_chat__chat_id_26f50f_idx')],
            },
        ),
    ]
