volumes:
  restaurantes_local_postgres_data: {}
  restaurantes_local_postgres_data_backups: {}
  restaurantes_local_redis_data: {}
  restaurantes_local_redisinsight_data: {}

services:
  django: &django
    build:
      context: ./backend
      dockerfile: ./compose/local/django/Dockerfile
    image: restaurantes_local_django
    container_name: restaurantes_local_django
    restart: unless-stopped
    depends_on:
      - redis
      - pgbouncer

    volumes:
      - ./backend:/app:z
    env_file:
      - ./backend/.envs/.local/.postgres
      - ./backend/.envs/.local/.django
      - ./backend/.env
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: ./backend
      dockerfile: ./compose/production/postgres/Dockerfile
    image: restaurantes_local_postgres
    restart: unless-stopped
    container_name: restaurantes_local_postgres
    volumes:
      - restaurantes_local_postgres_data:/var/lib/postgresql/18/docker
      - restaurantes_local_postgres_data_backups:/backups
    env_file:
      - ./backend/.envs/.local/.postgres

  pgbouncer:
    build:
      context: ./backend
      dockerfile: ./compose/production/pgbouncer/Dockerfile
    image: restaurantes_local_pgbouncer
    container_name: restaurantes_local_pgbouncer
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./backend/.envs/.local/.postgres
    ports:
      - '6432:6432'

  redis:
    image: docker.io/redis:7.2
    container_name: restaurantes_local_redis
    volumes:
      - restaurantes_local_redis_data:/data
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:2.48.0
    container_name: restaurantes_local_redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - restaurantes_local_redisinsight_data:/data
    depends_on:
      - redis

  celeryworker:
    <<: *django
    image: restaurantes_local_celeryworker
    container_name: restaurantes_local_celeryworker
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celeryworker
    restart: unless-stopped

  celerybeat:
    <<: *django
    image: restaurantes_local_celerybeat
    container_name: restaurantes_local_celerybeat
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celerybeat
    restart: unless-stopped

  flower:
    <<: *django
    image: restaurantes_local_flower
    container_name: restaurantes_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ./compose/local/Dockerfile
    image: restaurantes_local_frontend
    container_name: restaurantes_local_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Volumen anónimo para preservar node_modules
    env_file:
      - ./frontend/.env
    ports:
      - '5173:5173'
    depends_on:
      - django
    restart: unless-stopped
