# Generated by Django 6.0.3 on 2026-03-15 20:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryNavigationStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuLayoutOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QrTargetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('display_name', models.CharField(max_length=180)),
                ('legal_name', models.CharField(blank=True, max_length=180)),
                ('nit', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='platform_config.subscriptionplan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='restaurants.restaurantcategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='restaurants.restaurantstatus')),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('qr_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_codes', to='restaurants.qrtargettype')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant_qr_codes',
            },
        ),
        migrations.CreateModel(
            name='RestaurantAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line1', models.CharField(max_length=220)),
                ('line2', models.CharField(blank=True, max_length=220)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant_addresses',
            },
        ),
        migrations.CreateModel(
            name='RestaurantBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo_url', models.URLField(blank=True)),
                ('cover_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(blank=True, max_length=15)),
                ('secondary_color', models.CharField(blank=True, max_length=15)),
                ('dark_mode_enabled', models.BooleanField(default=False)),
                ('cart_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brandings', to='restaurants.cartposition')),
                ('category_navigation_style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brandings', to='restaurants.categorynavigationstyle')),
                ('menu_layout_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brandings', to='restaurants.menulayoutoption')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant_brandings',
            },
        ),
        migrations.CreateModel(
            name='RestaurantDeliverySetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_delivery_from_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_min_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_max_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('coverage_radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_setting', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant_delivery_settings',
            },
        ),
        migrations.CreateModel(
            name='RestaurantOrderCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_enabled', models.BooleanField(default=True)),
                ('pickup_enabled', models.BooleanField(default=True)),
                ('table_order_enabled', models.BooleanField(default=False)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_capability', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant_order_capabilities',
            },
        ),
        migrations.CreateModel(
            name='RestaurantPaymentSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_enabled', models.BooleanField(default=True)),
                ('pse_enabled', models.BooleanField(default=False)),
                ('cash_enabled', models.BooleanField(default=True)),
                ('nequi_enabled', models.BooleanField(default=False)),
                ('invoice_enabled', models.BooleanField(default=False)),
                ('invoice_prefix', models.CharField(blank=True, max_length=20)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_setting', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant_payment_settings',
            },
        ),
        migrations.CreateModel(
            name='RestaurantSocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant_social_links',
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_number', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='restaurants.tablestatus')),
            ],
            options={
                'db_table': 'restaurant_tables',
            },
        ),
        migrations.CreateModel(
            name='RestaurantHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant_hours',
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'weekday'), name='uniq_restaurant_weekday')],
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['status'], name='restaurants_status__73b1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['owner'], name='restaurants_owner_i_229fd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.UniqueConstraint(fields=('restaurant', 'table_number'), name='uniq_restaurant_table_number'),
        ),
    ]
