# Generated by Django 6.0.3 on 2026-03-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='currency_code',
            field=models.CharField(default='COP', max_length=3),
        ),
    ]
