# Generated by Django 6.0.3 on 2026-03-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantbranding',
            name='filters_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantbranding',
            name='image_size',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantbranding',
            name='search_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantbranding',
            name='show_descriptions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantbranding',
            name='show_prices',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantbranding',
            name='show_tags',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantbranding',
            name='slogan',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='restaurantbranding',
            name='welcome_message',
            field=models.TextField(blank=True),
        ),
    ]
