# Generated by Django 6.0.3 on 2026-03-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantbranding_filters_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantbranding',
            name='cover_file',
            field=models.FileField(blank=True, upload_to='restaurant-branding/'),
        ),
        migrations.AddField(
            model_name='restaurantbranding',
            name='logo_file',
            field=models.FileField(blank=True, upload_to='restaurant-branding/'),
        ),
    ]
