#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

mkdir -p /app/logs

python /app/manage.py collectstatic --noinput

exec gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn_worker.UvicornWorker
