# Generated by Django 6.0.3 on 2026-05-19 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_config', '0002_platformsetting_chat_image_allowed_mimes_and_more'),
        ('restaurants', '0008_new_operator_modules_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'billing_features',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency_code', models.CharField(default='COP', max_length=3)),
                ('is_free', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('billing_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_plans', to='platform_config.billingperiod')),
            ],
            options={
                'db_table': 'billing_plans',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PlanChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('superseded', 'Supersedida')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('current_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_from', to='billing.plan')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_requests_made', to=settings.AUTH_USER_MODEL)),
                ('requested_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_to', to='billing.plan')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_change_requests', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'billing_plan_change_requests',
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='billing.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_plan_features',
            },
        ),
        migrations.CreateModel(
            name='RestaurantFeatureOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('admin', 'Admin'), ('trial', 'Trial'), ('legacy', 'Legacy')], default='admin', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_overrides', to='billing.feature')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'billing_restaurant_feature_overrides',
            },
        ),
        migrations.CreateModel(
            name='RestaurantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Activa'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('override_trial_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_provider', models.CharField(blank=True, max_length=60)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='restaurants.restaurant')),
                ('scheduled_downgrade_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_downgrades', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_restaurant_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('trial_started', 'Trial iniciado'), ('trial_expired', 'Trial expirado'), ('plan_changed', 'Plan cambiado'), ('subscription_cancelled', 'Suscripción cancelada'), ('subscription_downgraded', 'Suscripción degradada'), ('request_created', 'Solicitud creada'), ('request_approved', 'Solicitud aprobada'), ('request_rejected', 'Solicitud rechazada'), ('override_set', 'Override establecido')], max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_events_acted', to=settings.AUTH_USER_MODEL)),
                ('new_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_to', to='billing.plan')),
                ('old_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_from', to='billing.plan')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_events', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'billing_subscription_events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrialConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('default_trial_days', models.PositiveSmallIntegerField(default=14)),
                ('trial_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_configs', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_trial_config',
            },
        ),
        migrations.CreateModel(
            name='TrialFeatureDefault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('can_delete', models.BooleanField(default=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_feature_defaults', to='billing.feature')),
                ('trial_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_feature_defaults', to='billing.trialconfig')),
            ],
            options={
                'db_table': 'billing_trial_feature_defaults',
            },
        ),
        migrations.CreateModel(
            name='FeatureDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='billing.feature')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='billing.feature')),
            ],
            options={
                'db_table': 'billing_feature_dependencies',
                'constraints': [models.UniqueConstraint(fields=('feature', 'depends_on'), name='uniq_feature_dependency'), models.CheckConstraint(condition=models.Q(('feature', models.F('depends_on')), _negated=True), name='no_self_dependency')],
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_free', True)), fields=('is_free',), name='uniq_active_free_plan'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='uniq_default_plan'),
        ),
        migrations.AddConstraint(
            model_name='planfeature',
            constraint=models.UniqueConstraint(fields=('plan', 'feature'), name='uniq_plan_feature'),
        ),
        migrations.AddConstraint(
            model_name='restaurantfeatureoverride',
            constraint=models.UniqueConstraint(fields=('restaurant', 'feature'), name='uniq_restaurant_feature_override'),
        ),
        migrations.AddConstraint(
            model_name='trialfeaturedefault',
            constraint=models.UniqueConstraint(fields=('trial_config', 'feature'), name='uniq_trial_feature_default'),
        ),
    ]
