# Generated by Django 6.0.3 on 2026-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trialconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_enabled', True)), fields=('is_enabled',), name='uniq_trial_config_enabled_true'),
        ),
        migrations.AddConstraint(
            model_name='trialconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_enabled', False)), fields=('is_enabled',), name='uniq_trial_config_enabled_false'),
        ),
    ]
