# Generated by Django 6.0.3 on 2026-03-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menucategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemimage',
            name='image_file',
            field=models.FileField(blank=True, upload_to='menu-items/'),
        ),
        migrations.AlterField(
            model_name='menuitemimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
