# Generated by Django 6.0.3 on 2026-05-16 23:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitemimage_image_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemLoyaltyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allows_points_redemption', models.BooleanField(default=False)),
                ('min_points_redeemable', models.PositiveIntegerField(default=0)),
                ('max_points_redeemable', models.PositiveIntegerField(blank=True, null=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_config', to='menu.menuitem')),
            ],
            options={
                'db_table': 'menu_item_loyalty_configs',
            },
        ),
    ]
