# Generated by Django 6.0.3 on 2026-05-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='chat_image_allowed_mimes',
            field=models.CharField(default='image/jpeg,image/png,image/webp', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='chat_image_max_mb',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='chat_images_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='chat_post_close_purge_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
