# Generated by Django 6.0.3 on 2026-05-13 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
        ('restaurants', '0006_operador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantLoyaltySetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('currency_unit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points_earned', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'restaurant_loyalty_settings',
            },
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='loyaltyaccount',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='uniq_user_restaurant_loyalty'),
        ),
        migrations.AddField(
            model_name='restaurantloyaltysetting',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_setting', to='restaurants.restaurant'),
        ),
    ]
