# Generated by Django 6.0.3 on 2026-05-16 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_restaurantloyaltysetting_loyaltyaccount_restaurant_and_more'),
        ('orders', '0002_order_customer_email_order_customer_name_and_more'),
        ('restaurants', '0008_new_operator_modules_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyaltytier',
            options={},
        ),
        migrations.AddField(
            model_name='loyaltyredemption',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_redemptions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='loyaltyredemption',
            name='points_applied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loyaltyreward',
            name='available_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltyreward',
            name='max_per_user',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltyreward',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_tiers', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantloyaltysetting',
            name='max_points_per_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantloyaltysetting',
            name='max_redeemable_points_per_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantloyaltysetting',
            name='point_redeem_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='restaurantloyaltysetting',
            name='vip_threshold_orders',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='loyaltytier',
            name='code',
            field=models.CharField(max_length=60),
        ),
        migrations.AddConstraint(
            model_name='loyaltytier',
            constraint=models.UniqueConstraint(fields=('restaurant', 'code'), name='uniq_loyalty_tier_restaurant_code'),
        ),
    ]
