# Generated by Django 6.0.3 on 2026-05-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_data_migrate_tiers_per_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytier',
            name='code',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
