# Generated by Django 6.0.3 on 2026-05-18 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_alter_loyaltytier_code'),
        ('orders', '0002_order_customer_email_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyredemption',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_redemptions', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='cap_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='points_uncapped',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantloyaltysetting',
            name='max_customer_points_balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
