# Generated by Django 6.0.3 on 2026-05-19 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_soft_cap_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyredemption',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loyaltyredemption',
            name='loyalty_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='loyalty.loyaltyreward'),
        ),
    ]
