# Generated by Django 6.0.3 on 2026-05-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_loyalty_redemption_optional_reward_and_is_direct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytier',
            name='code',
            field=models.CharField(max_length=60),
        ),
    ]
