# Generated by Django 6.0.3 on 2026-05-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0008_loyaltytier_code_not_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantloyaltysetting',
            name='min_payment_denomination',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
